python train.py \
    --model "/opt/data02/zhan/models/bert/albert_chinese_small" \
    --train_path "data/intention/train.txt" \
    --dev_path "data/intention/dev.txt" \
    --save_dir "checkpoints/intention" \
    --img_log_dir "logs/intention" \
    --img_log_name "BERT" \
    --num_labels 2 \
    --batch_size 8 \
    --max_seq_len 128 \
    --valid_steps 50 \
    --logging_steps 10 \
    --num_train_epochs 20 \
    --device "cuda:0"